"""
atlas_gitlab_adapter.py — GitLab adapter for the Atlas capstone.

The capstone uses GitHub (gh CLI) by default. This adapter swaps in GitLab's
REST API, demonstrating how to port the integration layer without touching
the agent's reasoning or the LangGraph pipeline.

The only node that changes is fetch_issue_node (reads from GitLab instead of
GitHub) and publish_pr_node (creates a GitLab Merge Request instead of a PR).
Everything else — planner, coder, tester, reviewer — is identical.

Usage:
    python atlas_gitlab_adapter.py --issue 42 --project mygroup/myrepo

Requires: pip install python-gitlab anthropic
"""

import argparse
import json
import os
import sys
from pathlib import Path

import anthropic
import gitlab

sys.path.insert(0, str(Path(__file__).parent.parent))
from atlas_capstone import AtlasState, build_graph

client     = anthropic.Anthropic()
gl         = gitlab.Gitlab(
    os.environ.get("GITLAB_URL", "https://gitlab.com"),
    private_token=os.environ["GITLAB_TOKEN"],
)


# ── GitLab-specific node overrides ────────────────────────────────────

def fetch_gitlab_issue(state: AtlasState) -> dict:
    """Fetch a GitLab issue instead of a GitHub issue."""
    project = gl.projects.get(state["repo"])
    issue   = project.issues.get(state["issue_number"])
    return {
        "issue": {
            "title":  issue.title,
            "body":   issue.description or "",
            "labels": issue.labels,
            "iid":    issue.iid,
        }
    }


def publish_gitlab_mr(state: AtlasState) -> dict:
    """Create a GitLab Merge Request instead of a GitHub PR."""
    if not state.get("approved"):
        print("\nMR creation cancelled by reviewer.")
        return {}

    if state.get("dry_run"):
        print("\n[dry-run] Would create Merge Request")
        return {}

    project    = gl.projects.get(state["repo"])
    issue_iid  = state["issue"].get("iid", state["issue_number"])
    branch     = f"atlas/issue-{issue_iid}"
    issue_title = state["issue"].get("title", f"Issue #{issue_iid}")

    # Create branch (assumes changes committed locally and pushed)
    try:
        project.branches.create({"branch": branch, "ref": "main"})
    except gitlab.GitlabCreateError:
        pass  # Branch may already exist

    # Upload file changes via GitLab API
    for filename, content in (state.get("code_changes") or {}).items():
        try:
            project.files.create({
                "file_path":     filename,
                "branch":        branch,
                "content":       content,
                "commit_message": f"Atlas v0.20: {filename}",
            })
        except gitlab.GitlabCreateError:
            project.files.update(filename, {
                "branch":        branch,
                "content":       content,
                "commit_message": f"Atlas v0.20: update {filename}",
            })

    mr = project.mergerequests.create({
        "source_branch":        branch,
        "target_branch":        "main",
        "title":                f"fix: {issue_title}",
        "description":          (
            f"Closes #{issue_iid}\n\n"
            "Generated by Atlas v0.20\n\n"
            f"Files changed: {', '.join(state.get('code_changes', {}).keys())}"
        ),
        "remove_source_branch": True,
    })

    print(f"\n✅ Merge Request created: {mr.web_url}")
    return {}


# ── Build GitLab-adapted graph ────────────────────────────────────────

def build_gitlab_graph():
    """Return the Atlas graph with GitLab node overrides."""
    from langgraph.graph import END, START, StateGraph
    from langgraph.graph.message import add_messages
    from atlas_capstone import (
        coder_node, tester_node, reviewer_node,
        human_approval_node, check_tests, check_review,
    )

    g = StateGraph(AtlasState)
    g.add_node("fetch_issue",    fetch_gitlab_issue)   # GitLab override
    g.add_node("planner",        __import__("atlas_capstone").planner_node)
    g.add_node("coder",          coder_node)
    g.add_node("tester",         tester_node)
    g.add_node("reviewer",       reviewer_node)
    g.add_node("human_approval", human_approval_node)
    g.add_node("publish_mr",     publish_gitlab_mr)    # GitLab override

    g.add_edge(START, "fetch_issue")
    g.add_edge("fetch_issue", "planner")
    g.add_edge("planner", "coder")
    g.add_edge("coder", "tester")
    g.add_conditional_edges("tester", check_tests, {
        "pass": "reviewer", "fail": "coder", "max_retries": END,
    })
    g.add_conditional_edges("reviewer", check_review, {
        "approved": "human_approval", "needs_revision": "coder", "max_retries": END,
    })
    g.add_edge("human_approval", "publish_mr")
    g.add_edge("publish_mr", END)

    return g.compile()


def main():
    parser = argparse.ArgumentParser(description="Atlas v0.20 — GitLab Adapter")
    parser.add_argument("--issue",   type=int, required=True)
    parser.add_argument("--project", required=True, help="GitLab project path (group/repo)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print(f"Atlas v0.20 (GitLab) — Issue #{args.issue} in {args.project}")

    graph = build_gitlab_graph()
    state: AtlasState = {
        "messages":     [],
        "repo":         args.project,
        "issue_number": args.issue,
        "issue":        {},
        "plan":         [],
        "current_step": 0,
        "code_changes": {},
        "test_results": {},
        "review":       {},
        "approved":     False,
        "retry_count":  0,
        "dry_run":      args.dry_run,
    }
    graph.invoke(state)


if __name__ == "__main__":
    main()
